version: '3'
services:
  server:
    build: .
    working_dir: /usr/src/app
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000"]
    command: runServer.sh
